<?php
namespace LTPet\Pets\WalkingPets;

use pocketmine\network\protocol\PlayerListPacket;
use pocketmine\network\protocol\AddPlayerPacket;
use pocketmine\network\protocol\EntityEventPacket;
use pocketmine\level\particle\HeartParticle;
use pocketmine\utils\UUID;
use pocketmine\entity\Entity;
use pocketmine\entity\Effect;
use pocketmine\item\Item;
use pocketmine\Player;
use pocketmine\level\Level;

use LTPet\Main;
/*
*	NPC类
*/
class LTNPC extends WalkingPet{
	const NETWORK_ID = 63;

	public $width = 0.6;
	public $height = 1.8;
	public $length = 0.5;
	public $name = '女仆';
	public $eyeHeight = 1.62;
	protected $uid = null;
	protected $spluttered = null;
	protected $splutteredCountdown = 0;
	protected $splutteredCount = 0;
	public function __construct($level, $nbt, Player $owner, $att){
		parent::__construct($level,$nbt, $owner, $att);
		$this->uid=UUID::fromRandom();
	}
	public function getSpluttered(){
		return $this->spluttered;
	}
	public function linkEntity(Player $player){//啪啪啪
		if($this->getSpluttered()===null) {
			if($player->getPleasureEvent()){
				return $player->sendMessage('§c你正在跟你的伴侣啪啪啪呢！');
			}
			if($player->getLinkedEntity()){
				return $player->sendMessage('§c你当前是骑乘状态 无法完成这个操作!');
			}
			if($this->getAtt()->getLove()<=10){
				return $player->sendMessage('§c亲密度不足！');
			}
			if($player!==$this->getOwner()){
				// return;//TODO 女仆不被主人啪啪啪 [强奸]
				if($player->getMoney()<10000){
					return $player->sendMessage('§c你的钱不够啪啪啪别人女仆！');
				}
				$player->reduceMoney(10000, '强奸女仆');
                $player->sendMessage('§c你的啪啪啪别人的女仆，女仆收费10000已扣除！');
				$this->getOwner()->sendMessage('§l§a['.$this->getPetName().'§r§a]§d主人我卖淫为你增加了10000收入~');
				$this->getOwner()->addMoney(10000, '女仆收入');
                $this->getOwner()->newProgress('肮脏的收入');//新成就
			}
            $this->spluttered = $player;
            $player->teleport($this, $player->getYaw(), $player->getPitch(), false);
            $this->setDataProperty(29, self::DATA_TYPE_POS, [$this->x, $this->y, $this->z]);
            $this->setDataFlag(27, 1, true, self::DATA_TYPE_BYTE);//躺下
			$player->addEffect(Effect::getEffect(10)->setDuration(20*20)->setAmplifier(4));
            $player->teleport($this, $player->getYaw(), $player->getPitch(), false);
			$player->setDataFlag(Entity::DATA_FLAGS, Entity::DATA_FLAG_IMMOBILE, true);//禁止移动
			$this->splutteredCountdown=100+$this->getAtt()->getLove()*10;//啪啪啪时间 主人5秒加好感度
			
			$player->setLinkedEntity($this);
            return;
        }
	}
	public function onUpdate($currentTick){
		if($this->getSpluttered()!==null){//如果是啪啪啪状态
			if(!($this->owner instanceof Player) or $this->owner->closed) {
				$this->close();
				return false;
			}
			if($this->closed) {
				return false;
			}
			$player=$this->getSpluttered();
			if($this->getServer()->getTick()%2===0){
				$player->setSneaking(true);//潜行
				$pk = new EntityEventPacket();
				$pk->event = EntityEventPacket::HURT_ANIMATION;//受伤动画
				$pk->eid=$this->getId();
				if(!mt_rand(0, 2)){
					foreach($this->getViewers() as $p){
						$p->dataPacket($pk);
						if($p===$this->owner){
							$p->sendMessage('§l§a['.$this->getPetName().'§r§a]§d'.self::CallBed());//叫声..
						}else{
							$p->sendMessage('§l§a['.$this->owner->getName().'的女仆'.$this->getPetName().'§r§a]§d'.self::CallBed());//叫声..
						}
					}
				}
				$player->getLevel()->addParticle(new HeartParticle($player));//爱心粒子
			}
			$this->splutteredCount++;
			if(--$this->splutteredCountdown<=0){
				if($this->splutteredCount<=200){//如果时间小于10秒
					$player->sendMessage('§l§a['.$this->owner->getName().'的女仆'.$this->getPetName().'§r§a]§d你太快了吧！');
				}
				$this->stopPapa();
			}
		}
		return parent::onUpdate($currentTick);
	}
    public function stopPapa()
    {
		if($this->getSpluttered()!==null){
		    /** @var Player $player */
			$player=$this->getSpluttered();
			if ($player === $this->getOwner()){
                $player->newProgress('感觉都一样');
            }else{
                $player->newProgress('追求刺激');
            }
			$player->removeEffect(10);
			$player->setLinkedEntity(null);
			$this->spluttered = null;
			$this->splutteredCountdown = 0;
			$this->splutteredCount = 0;
			$player->setDataFlag(Entity::DATA_FLAGS, Entity::DATA_FLAG_IMMOBILE, false);//允许移动
			$this->setDataProperty(29, self::DATA_TYPE_POS, [0, 0, 0]);
			$this->setDataFlag(27, 1, false, self::DATA_TYPE_BYTE);
		}
    }
	public function spawnTo(Player $player){
		if(isset($this->hasSpawned[$player->getLoaderId()]) or !isset($player->usedChunks[Level::chunkHash($this->chunk->getX(), $this->chunk->getZ())]))return;
		$info=$this->getAtt()->getInfo();
		if(!isset($info['skin']))$info['skin']='';
		$this->getAtt()->setInfo($info);
		if($info['skin']!==''){
			$this->server->updatePlayerListData($this->uid, $this->getId(), '§d'.$this->owner->getName().'的女仆§e'.$this->getPetName(), 'Standard_CustomSlim', Main::getInstance()->skins[$info['skin']]);
		}else{
			$this->server->updatePlayerListData($this->uid, $this->getId(), '§d'.$this->owner->getName().'的女仆§e'.$this->getPetName(), 'Standard_CustomSlim', base64_decode('AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACiaEb/o25G/6RmSP+pb1D/rnVY/6FvSv+kakT/n2dG/5pmQv+WYD//nWE9/5VmQP+WZ0X/lWZD/5tiPv+UZkb/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAnmtN/6JtU/+ugF3/sYFY/6t5X/+yf1r/qnRR/6ZvSP+bX0L/nGhH/5VhP/+UZz//oWY//5ZnPf+ZYT7/oWdF/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKRtUf+pgFv/sYVi/7aJbP+6i2X/r4Fn/6p8X/+qbUz/m2I//51lP/+YYUb/m2U//5xmP/+dZEL/n2lG/5pkRP8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACscVn/rIFf/7SLaf+4iHH/votv/7GDaP+reFv/rnZU/6BlQf+dY0f/l2VD/5tnRv+gZ0T/lmFA/5pmQP+fYT//AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAq3RW/7CAX/+1gmr/uIhq/7iJbP+1g2r/s3le/6l4Vf+cZkj/7Na3//LWwv/z4cT/89nJ/+3Yxv/u1L7/nWlA/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKpvU/+wgF3/s39m/7Z8YP+xfV//s39i/7F7W/+pcEv/mmpE/+3Vuv/p1bj/8dzB/+7cwP/p0rv/59Wz/5tePv8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACebET/qW5S/6x9Xf+tgFv/sHxb/6+AYP+idE//nW9I/5ZmQ//u07D/6dC0//DTvP/sz7n/5tO6/+3QtP+eakL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAApG5L/55oSv+ob1H/qnNP/6dxT/+jbVP/ompG/59uTP+aYkf/6sut/+7Ss//r1bL/6NK5/+3Rsf/nyqv/n2pF/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACnck7/rHlb/6NyUv+xfVz/o3ZM/6Z0WP+jdFD/p29P/7eQbf+2iWj/s4Vj/6lyWf+pcVL/qXNU/6J1TP+mdkz/oW5I/7F5Wv+pdVD/roFf/6ZwTv+peV3/onNO/51rTP+nclH/qnZT/6Z2Uf+leVj/nWZL/6VtUv+qbkv/oG5G/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACLYD7/nGE//6BqSv+fYET/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAqnta/65/Xv+qel7/s4lm/7R/Y/+vfWb/r4Fa/6N1Tv+4hm7/sn1h/659XP+ocFH/pnBS/6N1Uf+odk//pHVQ/7B+XP+yfGf/q3tc/7aBaP+ygF//r35h/6qAX/+kdk7/q3xc/7Z9Yv+ueV3/r4Ne/6t/X/+we17/snpa/6RvU/8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACYZ0P/JSgn/6t3Vf+qc1b/p3JP/5xsSf+RWjz/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAK9/Xf+1im3/sodl/7qIb/+yi27/toNs/7eCa/+tfmH/qG9M/6t1Vf+qdlP/qnBR/6pvTf+kc07/p25Q/6J2Tv+ugV//todp/7GBav+4iWr/uIZq/7aKa/+1gGf/qXZP/7B9WP+yhG3/sYNj/7SGZ/+xfmf/soRp/619Zf+tfV3/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACbZ0n/o2hM/xgWGf8vMjP/pW9M/6xtTv+RXUX/qG1O/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACuhWL/t45s/72Ocf+9j2//todm/7iLbv+5h2n/rHlb/6ZwUP+jbk3/oW5M/6VvTv/w1rj/8s+w//XJrf+kdkv/s3xj/72Lav+5i2r/uJFu/7yIav+/kXX/s4dq/7J/YP+2gWD/t4xv/7aGa/+4h3L/toRt/7iLbf+1gGj/q3hf/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMjI0/xoVFv+dbkz/mGFC/5NhQf+QYkP/AAAAAJRgQ/8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAsnlZ/7aKaP+2i2n/t4Vo/62AX/+2fV//qn1h/6lvUv+qbkv/pXZT/6lzUf/32bj/+d3B/zE0Lf86Oj3/o3RR/695WP+0gGH/sHhf/7iLaf+0gmf/vY1q/7F+Xv+odlL/r3la/7eEY/+ugGD/todt/7KFYP+0iGn/sXxk/7B5Xf8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJlpSP8jJSX/kGI8/49fRP8AAAAAAAAAAAAAAACQX0L/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAK96Wf+uhV7/toBm/62BYP+ndk7/sYFe/6RtUv+dbET/qHZR/6FtT/8jKSn/+OTL///p2P8rKSb/8evn/0RCPv+rdUz/qnZV/6lvU/+rel7/rHhd/7ODY/+vgV7/pnRU/66AW/+qelz/sIFf/62EZf+yeWD/snxf/694W/+qcFH/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACgZEb/kmM7/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACic0//s3xg/6x8W/+rcVr/pWpN/6p6V/+kb0n/oGVA/6RvS//d4Nv/FhsS//fjyv/+6dX/Fhsb//fSuf+mc07/o2dM/6JvU/+qdk3/qnFN/6Z2Tf+ufV3/pW5M/6FqR/+nclD/qXlf/6V2Uf+xgFv/rnlV/7F+WP+icFL/nWtF/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAh10//41eOv8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAo2VD/6FmSv+iZkz/omhJ/5xgQv+jbE3/mWlG/5VgQv+lb0z//7+t///Mt//31MH/+NbA//3Mu//8v6//pm1O/5xnQf+eb0z/l2dF/6RsSP+cZUr/pGdL/6BtSf+eZET/pWZE/6R2Tf+pbk3/pnJR/6FxUf+ncFL/pWdM/6VsSP8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACGWTr/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAb0U0/2tJNP9rRSv/bEox/2hFLP9xSCz/bEov/2hLMP8+Njb/Ozw//0NGQP9HQ0L/R0FC/0Y+Pf87OTv/Pjk6/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHhNNP+DWzz/i1pA/4paOf+SYT3/kWI//4xgOP92TDf/ODc8/z9DQv9EQj//RkFJ/0dHRv9BRkb/OkJA/z02PP8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPfSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPfSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB3UDj/lWZD//PYv//x28n/8eDL/+/cwv+VXjz/fU4w/zc3Pv9DRj//RENH/0pMRv9IRUX/QkBH/0U+Pf88Njn/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAfFM1/5tlSP/z1bv/9d69//jVwv/02bz/oGZB/4FSOv8/PDr/PUZA/0JGR/9GS0T/REhL/0dFQ/8+RkH/Pz89/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/5seq/+7Gp//sxKX/6Mem/4thPP+hbkX/99K5//fSuf/30rn/99K5/6NmS/+SYkL/7MSq/+/Nq//syaz/5Min/6NlSP+lbUv/pmpR/6VsS/+ickn/pXFP/59tUv+gc0r/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/sw6X/7s6x/+jGqv/oyKb/99K5//fSuf/30rn/99K5/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/wyqv/9dS9//fSuf/s0rP/99K5//fSuf/30rn/99K5/+/Jrf/30rn/7syz/+nGq/+WZUH/pXFU//fSuf/30rn/99K5//fSuf+uclj/lWBA/+nKqf/y0a7/99K5//fSuf+iZkf/oG5J/6JqUP+rblP/o3BN/6dsSf+lc1H/oG5O//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/s0rr/99K5//fSuf/30rn/99K5//fSuf8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPfSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/69S1//fSuf/017//6865//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/mmRC//fSuf/30rn/99K5//fSuf/30rn/99K5/59oQ//30rn/99K5//fSuf/30rn/oW9O/6p9Vf+icUn/r31V/6duUf+seFP/pnJL/6ZxUP/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5/+zVuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5/6JqS/+seVX/rnZW/6t8U/+mdlf/qXVb/6tyTv+odVT/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/AAAA//fSuf/30rn/99K5//fSuf8AAAD/99K5//fSuf/30rn/99K5//fSuf+kcVL/q3ZU/6t4XP+weln/r3lb/7F+Xv+odlj/qHFT//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPfSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5/7F6Xf+sf1n/tYVf/6h9VP+0fWP/q3lU//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/rn1Y/6x7Wf+oelb/qXpZ//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf+pdFH/o3RM//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPfSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPfSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPfSuf8AAAAA99K5/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPfSuf8AAAAA99K5/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD30rn/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPfSuf8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8dO3//bUx//t1Lr/6su3//fSuf/30rn/99K5//TUvf8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPDUw//w38r/893I/+/Wvv/30rn/99K5//fSuf/30rn/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPfSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADw1Lz/+ODJ//HYwP/y0Lr/99K5//fSuf/30rn/99K5/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA69Kx/+7Qvv/w1rr/7Mq4//fSuf/30rn/99K5//fSuf8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA7cyz//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPfSuf/30rn/99K5//LSuv/z0bX/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA99K5/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD30rn/99K5/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPfSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD30rn/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPfSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPfSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=='));
		}
		$pk = new AddPlayerPacket();
		$pk->uuid = $this->uid;
		$pk->username = $this->getPetName();
		$pk->eid = $this->getId();
		$pk->x = $this->x;
		$pk->y = $this->y+$this->getEyeHeight();
		$pk->z = $this->z;
		$pk->speedX = 0;
		$pk->speedY = 0;
		$pk->speedZ = 0;
		$pk->yaw = $this->yaw;
		$pk->pitch = $this->pitch;
		$pk->item = Item::get(0);
		$pk->metadata = $this->dataProperties;     
		$player->dataPacket($pk);
		$this->hasSpawned[$player->getLoaderId()] = $player;
	}
    public function close()
    {
        if($this->closed)return;
		$this->server->removePlayerListData($this->uid);
        parent::close();
    }
	public static function CallBed(){
//		$message=[
//			'啊~',
//			'不要',
//			' ~~停',
//			'不要 ~~ 停',
//			'啊~ 爽~~',
//			'~ ~ 啊 ~哎呀~',
//			'用~ ~力~',
//			'主人，不要~',
//			'不要酱紫~',
//			'会~~坏掉的~',
//			'慢  ~点~',
//		];
//		return $message[array_rand($message)];
	}
}