<?php
namespace LTPet\Preview;

use pocketmine\Player;
use pocketmine\entity\Entity;
use pocketmine\item\Item;
use pocketmine\network\protocol\AddEntityPacket;
use pocketmine\network\protocol\RemoveEntityPacket;
use pocketmine\network\protocol\MoveEntityPacket;
use pocketmine\network\protocol\LevelEventPacket;
use pocketmine\network\protocol\MovePlayerPacket;
use pocketmine\network\protocol\AddPlayerPacket;
use pocketmine\network\protocol\PlayerListPacket;
use pocketmine\utils\UUID;
use pocketmine\math\Vector3;
use LTPet\Pets\WalkingPets\{
	LTRabbit,LTChicken,LTPig,LTSheep,LTWolf,LTVillager,LTOcelot,LTHorse,LTSilverfish,LTSlime,LTCreeper,LTNPC,LTLlama,LTSpider,LTSkeleton
};
use LTPet\Pets\FlyingPets\{
	LTWitherBoss,LTEnderDragon
};
use LTPet\Pet;

class PreviewPet extends Vector3{
	const LTRabbit=0;//兔子
	const LTChicken=1;//鸡
	const LTPig=2;//猪
	const LTSheep=3;//羊
	const LTWolf=4;//狼
	const LTVillager=5;//村民
	const LTOcelot=6;//豹猫
	const LTHorse=7;//马
	const LTWitherBoss=8;//凋零
	const LTEnderDragon=9;//末影龙
	const LTSilverfish=10;//蠢虫
	const LTSlime=11;//史莱姆
	const LTCreeper=12;//苦力怕
	const LTLlama=13;//草泥马
	const LTSpider=14;//蜘蛛
	const LTSkeleton=15;//骷髅
	const LTNPC=16;//NPC
	
	public static $PreviewPets=[];
	
	private $Position;
	private $ID;
	private $entityID;
	private $eid;
	private $height;
	private $UUID;
	private $need;
	private $info;
	private $name;
	public static function init(){
		self::$PreviewPets[self::LTRabbit]=new PreviewPet(self::LTRabbit, LTRabbit::NETWORK_ID, '兔子', 0);
		self::$PreviewPets[self::LTChicken]=new PreviewPet(self::LTChicken, LTChicken::NETWORK_ID, '鸡', 0);
		self::$PreviewPets[self::LTPig]=new PreviewPet(self::LTPig, LTPig::NETWORK_ID, '猪', 0);
		self::$PreviewPets[self::LTSheep]=new PreviewPet(self::LTSheep, LTSheep::NETWORK_ID, '羊', 0);
		self::$PreviewPets[self::LTWolf]=new PreviewPet(self::LTWolf, LTWolf::NETWORK_ID, '狼', 0);
		self::$PreviewPets[self::LTVillager]=new PreviewPet(self::LTVillager, LTVillager::NETWORK_ID, '村民', 0);
		self::$PreviewPets[self::LTOcelot]=new PreviewPet(self::LTOcelot, LTOcelot::NETWORK_ID, '豹猫', 0);
		self::$PreviewPets[self::LTHorse]=new PreviewPet(self::LTHorse, LTHorse::NETWORK_ID, '马', 0);
		self::$PreviewPets[self::LTWitherBoss]=new PreviewPet(self::LTWitherBoss, LTWitherBoss::NETWORK_ID , '凋零', 0);
		self::$PreviewPets[self::LTEnderDragon]=new PreviewPet(self::LTEnderDragon, LTEnderDragon::NETWORK_ID, '末影龙', 1.5);
		self::$PreviewPets[self::LTSilverfish]=new PreviewPet(self::LTSilverfish, LTSilverfish::NETWORK_ID, '蠢虫', 0);
		self::$PreviewPets[self::LTSlime]=new PreviewPet(self::LTSlime, LTSlime::NETWORK_ID, '史莱姆', 0);
		self::$PreviewPets[self::LTCreeper]=new PreviewPet(self::LTCreeper, LTCreeper::NETWORK_ID, '苦力怕', 0);
		self::$PreviewPets[self::LTLlama]=new PreviewPet(self::LTLlama, LTLlama::NETWORK_ID, '羊驼', 0);
		self::$PreviewPets[self::LTSpider]=new PreviewPet(self::LTSpider, LTSpider::NETWORK_ID, '蜘蛛', 0);
		self::$PreviewPets[self::LTSkeleton]=new PreviewPet(self::LTSkeleton, LTSkeleton::NETWORK_ID, '骷髅', 0);
		self::$PreviewPets[self::LTNPC]=new PreviewPet(self::LTNPC, LTNPC::NETWORK_ID, '女仆', 1.62);
	}
	public static function get($id){
		return self::$PreviewPets[$id]??null;
	}
	public function __construct($ID, $entityID, $name, $height=0){
		$this->ID=$ID;
		$this->height=$height;
		$this->entityID=$entityID;
		$this->name=$name;
		$this->eid=Entity::$entityCount++;
		$this->Position=new Vector3(740.5, 4+$height, 60.5);
		$this->need=Pet::getCount($this->getName());
		if($this->need===false){
			$this->info='§l§d限活动获得！';
		}else{
			$this->info='§l§d '.$this->getName().'§e需要：§l§c材料'.$this->getNeed()[0].' '.$this->getNeed()[1].'个';
		}
		if($this->getID()==self::LTNPC){
			$this->UUID=UUID::fromRandom();
		}
		parent::__construct($this->Position->getX(), $this->Position->getY(), $this->Position->getZ());
	}
	public static function getMax(){
		return count(self::$PreviewPets)-1;
	}
	public function getEid(){
		return $this->eid;
	}
	public function getName(){
		return $this->name;
	}
	public function getNeed(){
		return $this->need;
	}
	public function getID(){
		return $this->ID;
	}
	public function getEntityID(){
		return $this->entityID;
	}
	public function spawnTo(Player $player){
		$x=$this->getX()-$player->getX();
		$y=$this->getY()-$player->getY();
		$z=$this->getZ()-$player->getZ();
		$yaw=asin($x/sqrt($x*$x+$z*$z))/3.14*180;
		$pitch=round(asin($y/sqrt($x*$x+$z*$z+$y*$y))/3.14*180);
		if($z>0){
			$yaw=-$yaw+180;
		}
		$flags = 0;
		$flags |= 1 << Entity::DATA_FLAG_CAN_SHOW_NAMETAG;
		$flags |= 1 << Entity::DATA_FLAG_ALWAYS_SHOW_NAMETAG;
		$flags |= 1 << Entity::DATA_FLAG_IMMOBILE;
		$metadata = [
			Entity::DATA_FLAGS => [Entity::DATA_TYPE_LONG, $flags],
			Entity::DATA_AIR => [Entity::DATA_TYPE_SHORT, 400],
			Entity::DATA_NAMETAG => [Entity::DATA_TYPE_STRING, $this->info],
			Entity::DATA_LEAD_HOLDER_EID => [Entity::DATA_TYPE_LONG, -1],
		];  
		if($this->getID()===self::LTNPC){//NPC
			$pk = new AddPlayerPacket();
			$pk->uuid = $this->UUID;
			$pk->username = 'test';
			$pk->item = Item::get(276);
			$pk->y = $this->getY()-$this->height;
		}else{
			$pk = new AddEntityPacket();
			$pk->type = $this->getEntityID();
			$pk->y = $this->getY();
		}
		$pk->metadata = $metadata;
		if($this->getName()=='末影龙'){
			if($yaw > 0){
				$yaw=$yaw - 180;
			}elseif($yaw < 0){
				$yaw=$yaw + 180;
			}
			$pk->metadata[Entity::DATA_SCALE] = [Entity::DATA_TYPE_FLOAT, 0.3];
		}
		$pk->yaw = $yaw;
		$pk->pitch = $pitch;
		$pk->eid = $this->eid;
		$pk->x = $this->getX();
		$pk->z = $this->getZ();
		$pk->speedX = 0;
		$pk->speedY = 0;
		$pk->speedZ = 0;
		$pk->pitch = $pitch;
		$player->dataPacket($pk);
		if($this->getID()===self::LTNPC){
			$pk = new PlayerListPacket();
			$pk->type = PlayerListPacket::TYPE_ADD;
			$pk->entries[] = [$this->UUID, $this->eid, '§d预览女仆', 'Standard_CustomSlim', 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACiaEb/o25G/6RmSP+pb1D/rnVY/6FvSv+kakT/n2dG/5pmQv+WYD//nWE9/5VmQP+WZ0X/lWZD/5tiPv+UZkb/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAnmtN/6JtU/+ugF3/sYFY/6t5X/+yf1r/qnRR/6ZvSP+bX0L/nGhH/5VhP/+UZz//oWY//5ZnPf+ZYT7/oWdF/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKRtUf+pgFv/sYVi/7aJbP+6i2X/r4Fn/6p8X/+qbUz/m2I//51lP/+YYUb/m2U//5xmP/+dZEL/n2lG/5pkRP8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACscVn/rIFf/7SLaf+4iHH/votv/7GDaP+reFv/rnZU/6BlQf+dY0f/l2VD/5tnRv+gZ0T/lmFA/5pmQP+fYT//AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAq3RW/7CAX/+1gmr/uIhq/7iJbP+1g2r/s3le/6l4Vf+cZkj/7Na3//LWwv/z4cT/89nJ/+3Yxv/u1L7/nWlA/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKpvU/+wgF3/s39m/7Z8YP+xfV//s39i/7F7W/+pcEv/mmpE/+3Vuv/p1bj/8dzB/+7cwP/p0rv/59Wz/5tePv8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACebET/qW5S/6x9Xf+tgFv/sHxb/6+AYP+idE//nW9I/5ZmQ//u07D/6dC0//DTvP/sz7n/5tO6/+3QtP+eakL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAApG5L/55oSv+ob1H/qnNP/6dxT/+jbVP/ompG/59uTP+aYkf/6sut/+7Ss//r1bL/6NK5/+3Rsf/nyqv/n2pF/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACnck7/rHlb/6NyUv+xfVz/o3ZM/6Z0WP+jdFD/p29P/7eQbf+2iWj/s4Vj/6lyWf+pcVL/qXNU/6J1TP+mdkz/oW5I/7F5Wv+pdVD/roFf/6ZwTv+peV3/onNO/51rTP+nclH/qnZT/6Z2Uf+leVj/nWZL/6VtUv+qbkv/oG5G/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACLYD7/nGE//6BqSv+fYET/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAqnta/65/Xv+qel7/s4lm/7R/Y/+vfWb/r4Fa/6N1Tv+4hm7/sn1h/659XP+ocFH/pnBS/6N1Uf+odk//pHVQ/7B+XP+yfGf/q3tc/7aBaP+ygF//r35h/6qAX/+kdk7/q3xc/7Z9Yv+ueV3/r4Ne/6t/X/+we17/snpa/6RvU/8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACYZ0P/JSgn/6t3Vf+qc1b/p3JP/5xsSf+RWjz/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAK9/Xf+1im3/sodl/7qIb/+yi27/toNs/7eCa/+tfmH/qG9M/6t1Vf+qdlP/qnBR/6pvTf+kc07/p25Q/6J2Tv+ugV//todp/7GBav+4iWr/uIZq/7aKa/+1gGf/qXZP/7B9WP+yhG3/sYNj/7SGZ/+xfmf/soRp/619Zf+tfV3/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACbZ0n/o2hM/xgWGf8vMjP/pW9M/6xtTv+RXUX/qG1O/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACuhWL/t45s/72Ocf+9j2//todm/7iLbv+5h2n/rHlb/6ZwUP+jbk3/oW5M/6VvTv/w1rj/8s+w//XJrf+kdkv/s3xj/72Lav+5i2r/uJFu/7yIav+/kXX/s4dq/7J/YP+2gWD/t4xv/7aGa/+4h3L/toRt/7iLbf+1gGj/q3hf/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMjI0/xoVFv+dbkz/mGFC/5NhQf+QYkP/AAAAAJRgQ/8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAsnlZ/7aKaP+2i2n/t4Vo/62AX/+2fV//qn1h/6lvUv+qbkv/pXZT/6lzUf/32bj/+d3B/zE0Lf86Oj3/o3RR/695WP+0gGH/sHhf/7iLaf+0gmf/vY1q/7F+Xv+odlL/r3la/7eEY/+ugGD/todt/7KFYP+0iGn/sXxk/7B5Xf8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJlpSP8jJSX/kGI8/49fRP8AAAAAAAAAAAAAAACQX0L/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAK96Wf+uhV7/toBm/62BYP+ndk7/sYFe/6RtUv+dbET/qHZR/6FtT/8jKSn/+OTL///p2P8rKSb/8evn/0RCPv+rdUz/qnZV/6lvU/+rel7/rHhd/7ODY/+vgV7/pnRU/66AW/+qelz/sIFf/62EZf+yeWD/snxf/694W/+qcFH/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACgZEb/kmM7/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACic0//s3xg/6x8W/+rcVr/pWpN/6p6V/+kb0n/oGVA/6RvS//d4Nv/FhsS//fjyv/+6dX/Fhsb//fSuf+mc07/o2dM/6JvU/+qdk3/qnFN/6Z2Tf+ufV3/pW5M/6FqR/+nclD/qXlf/6V2Uf+xgFv/rnlV/7F+WP+icFL/nWtF/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAh10//41eOv8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAo2VD/6FmSv+iZkz/omhJ/5xgQv+jbE3/mWlG/5VgQv+lb0z//7+t///Mt//31MH/+NbA//3Mu//8v6//pm1O/5xnQf+eb0z/l2dF/6RsSP+cZUr/pGdL/6BtSf+eZET/pWZE/6R2Tf+pbk3/pnJR/6FxUf+ncFL/pWdM/6VsSP8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACGWTr/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAb0U0/2tJNP9rRSv/bEox/2hFLP9xSCz/bEov/2hLMP8+Njb/Ozw//0NGQP9HQ0L/R0FC/0Y+Pf87OTv/Pjk6/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHhNNP+DWzz/i1pA/4paOf+SYT3/kWI//4xgOP92TDf/ODc8/z9DQv9EQj//RkFJ/0dHRv9BRkb/OkJA/z02PP8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPfSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPfSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB3UDj/lWZD//PYv//x28n/8eDL/+/cwv+VXjz/fU4w/zc3Pv9DRj//RENH/0pMRv9IRUX/QkBH/0U+Pf88Njn/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAfFM1/5tlSP/z1bv/9d69//jVwv/02bz/oGZB/4FSOv8/PDr/PUZA/0JGR/9GS0T/REhL/0dFQ/8+RkH/Pz89/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/5seq/+7Gp//sxKX/6Mem/4thPP+hbkX/99K5//fSuf/30rn/99K5/6NmS/+SYkL/7MSq/+/Nq//syaz/5Min/6NlSP+lbUv/pmpR/6VsS/+ickn/pXFP/59tUv+gc0r/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/sw6X/7s6x/+jGqv/oyKb/99K5//fSuf/30rn/99K5/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/wyqv/9dS9//fSuf/s0rP/99K5//fSuf/30rn/99K5/+/Jrf/30rn/7syz/+nGq/+WZUH/pXFU//fSuf/30rn/99K5//fSuf+uclj/lWBA/+nKqf/y0a7/99K5//fSuf+iZkf/oG5J/6JqUP+rblP/o3BN/6dsSf+lc1H/oG5O//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/s0rr/99K5//fSuf/30rn/99K5//fSuf8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPfSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/69S1//fSuf/017//6865//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/mmRC//fSuf/30rn/99K5//fSuf/30rn/99K5/59oQ//30rn/99K5//fSuf/30rn/oW9O/6p9Vf+icUn/r31V/6duUf+seFP/pnJL/6ZxUP/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5/+zVuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5/6JqS/+seVX/rnZW/6t8U/+mdlf/qXVb/6tyTv+odVT/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/AAAA//fSuf/30rn/99K5//fSuf8AAAD/99K5//fSuf/30rn/99K5//fSuf+kcVL/q3ZU/6t4XP+weln/r3lb/7F+Xv+odlj/qHFT//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPfSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5/7F6Xf+sf1n/tYVf/6h9VP+0fWP/q3lU//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/rn1Y/6x7Wf+oelb/qXpZ//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf+pdFH/o3RM//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPfSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPfSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPfSuf8AAAAA99K5/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPfSuf8AAAAA99K5/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD30rn/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPfSuf8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8dO3//bUx//t1Lr/6su3//fSuf/30rn/99K5//TUvf8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPDUw//w38r/893I/+/Wvv/30rn/99K5//fSuf/30rn/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPfSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADw1Lz/+ODJ//HYwP/y0Lr/99K5//fSuf/30rn/99K5/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA69Kx/+7Qvv/w1rr/7Mq4//fSuf/30rn/99K5//fSuf8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA7cyz//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPfSuf/30rn/99K5//LSuv/z0bX/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA99K5/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD30rn/99K5/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPfSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD30rn/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPfSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPfSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/99K5//fSuf/30rn/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=='];
			$player->dataPacket($pk);
		}
	}
	public function despawnFrom(Player $player){
		if($this->getID()===self::LTNPC)$player->getServer()->removePlayerListData($this->UUID,[$player]);
		$pk=new RemoveEntityPacket();
		$pk->eid=$this->eid;
		$player->dataPacket($pk);
	}
	public function updateSee(Player $player){//更新实体看的方向
		if($player->distance($this)>10)return true;
		$x=$this->getX()-$player->getX();
		$y=($this->getID()===self::LTNPC?$this->getY()-$this->height:$this->getY())-$player->getY();
		$z=$this->getZ()-$player->getZ();
		$yaw=asin($x/sqrt($x*$x+$z*$z))/3.14*180;
		$pitch=round(asin($y/sqrt($x*$x+$z*$z+$y*$y))/3.14*180);
		if($z>0){
			$yaw=-$yaw+180;
		}
		if($this->getID()===self::LTNPC){//NPC
			$pk=new MovePlayerPacket();
			$pk->bodyYaw=$yaw;
		}else{
			$pk=new MoveEntityPacket();
			if($this->name=='末影龙'){
				if($yaw > 0){
					$yaw=$yaw - 180;
				}elseif($yaw < 0){
					$yaw=$yaw + 180; 
				}
			}
			$pk->headYaw=$yaw;
		}
		$pk->eid=$this->eid;
		$pk->pitch=$pitch;
		$pk->yaw=$yaw;
		$pk->x=$this->getX();
		$pk->y=$this->getY();
		$pk->z=$this->getZ();
		$player->dataPacket($pk);
		return true;
	}
}